CREATE ROLE sgbd3_role NOT IDENTIFIED;
GRANT ALTER SESSION TO sgbd3_role;
GRANT CREATE DATABASE LINK TO sgbd3_role;
GRANT CREATE SESSION TO sgbd3_role;
GRANT CREATE PROCEDURE TO sgbd3_role;
GRANT CREATE SEQUENCE TO sgbd3_role;
GRANT CREATE TABLE TO sgbd3_role;
GRANT CREATE TRIGGER TO sgbd3_role;
GRANT CREATE TYPE TO sgbd3_role;
GRANT CREATE SYNONYM TO sgbd3_role;
GRANT CREATE VIEW TO sgbd3_role;
GRANT CREATE JOB TO sgbd3_role;
GRANT CREATE MATERIALIZED VIEW TO sgbd3_role;
GRANT EXECUTE ON sys.dbms_lock TO sgbd3_role;
GRANT EXECUTE ON sys.owa_opt_lock TO sgbd3_role;

CREATE USER cb IDENTIFIED BY oracle ACCOUNT UNLOCK;
ALTER USER cb QUOTA UNLIMITED ON users;
GRANT sgbd3_role TO cb;

CREATE USER cc IDENTIFIED BY oracle ACCOUNT UNLOCK;
ALTER USER cc QUOTA UNLIMITED ON users;
GRANT sgbd3_role TO cc;