package Vues;

import Tables.Movies;
import Tools.BDRenequinepolis;
import Tools.BdType;

import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Vector;

public class MainVue extends javax.swing.JFrame {
    private Component[] components;
    private BDRenequinepolis db;
    private Movies movie;
    private List<Movies> listMovies = new ArrayList<>();

    public MainVue() {
        initComponents();
        PanelDetails.setVisible(false);
        movie = new Movies();

        try {
            db = new BDRenequinepolis(BdType.Oracle);
        } catch (SQLException | IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idTF = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        rechLabel = new javax.swing.JLabel();
        PanelDetails = new javax.swing.JPanel();
        NbLabel = new javax.swing.JLabel();
        nomTF = new javax.swing.JTextField();
        acteurLabel = new javax.swing.JLabel();
        realisateurLabel = new javax.swing.JLabel();
        acteursTF = new javax.swing.JTextField();
        realisateurTB = new javax.swing.JTextField();
        anneeLabel = new javax.swing.JLabel();
        dateTF = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        criteresButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        ScrollPane1 = new javax.swing.JScrollPane();
        ResultatJTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 102));
        titleLabel.setText("Rennequinepolis");

        rechLabel.setText("Rechercher un film :");

        NbLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NbLabel.setText("Nom du film:");

        acteurLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        acteurLabel.setText("Acteurs :");

        realisateurLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        realisateurLabel.setText("Réalisateurs :");

        anneeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        anneeLabel.setText("Année :");

        javax.swing.GroupLayout PanelDetailsLayout = new javax.swing.GroupLayout(PanelDetails);
        PanelDetails.setLayout(PanelDetailsLayout);
        PanelDetailsLayout.setHorizontalGroup(PanelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(PanelDetailsLayout.createSequentialGroup().addContainerGap().addGroup(PanelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false).addComponent(NbLabel).addComponent(acteurLabel).addComponent(realisateurLabel)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(PanelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(realisateurTB, javax.swing.GroupLayout.Alignment.TRAILING).addComponent(acteursTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE).addComponent(nomTF, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)).addGap(80, 80, 80).addComponent(anneeLabel).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        PanelDetailsLayout.setVerticalGroup(PanelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(PanelDetailsLayout.createSequentialGroup().addContainerGap().addGroup(PanelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(NbLabel).addComponent(nomTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(anneeLabel).addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(PanelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(acteurLabel).addComponent(acteursTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(PanelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(realisateurLabel).addComponent(realisateurTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        criteresButton.setText("Plus de critères");
        criteresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criteresButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Rechercher");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        ResultatJTable.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{{null, null, null}, {null, null, null}, {null, null, null}, {null, null, null}}, new String[]{"Id", "titre", "Date sortie",}));
        ResultatJTable.setCellSelectionEnabled(true);
        ResultatJTable.setEnabled(false);
        ResultatJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResultatJTableMouseClicked(evt);
            }
        });
        ScrollPane1.setViewportView(ResultatJTable);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(121, 121, 121).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(41, 41, 41).addComponent(titleLabel)).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE).addGroup(layout.createSequentialGroup().addComponent(rechLabel).addGap(27, 27, 27).addComponent(criteresButton))).addGroup(layout.createSequentialGroup().addGap(108, 108, 108).addComponent(searchButton))).addGap(0, 0, Short.MAX_VALUE)).addComponent(ScrollPane1).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jSeparator2).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(PanelDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jSeparator1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jSeparator3))).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap().addComponent(titleLabel).addGap(18, 18, 18).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(rechLabel).addComponent(criteresButton)).addGap(18, 18, 18).addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(searchButton).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(PanelDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)).addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void criteresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criteresButtonActionPerformed
        if (PanelDetails.isVisible()) PanelDetails.setVisible(false);
        else PanelDetails.setVisible(true);// TODO add your handling code here:

    }//GEN-LAST:event_criteresButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        DefaultTableModel dtm = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        ResultSet res;
        try {
            if (!PanelDetails.isVisible()) res = db.getMovie(idTF.getText());
            else res = db.getMovies(nomTF.getText(), stringToArrayList(acteursTF.getText()), stringToArrayList(realisateurTB.getText()), dateTF.getText());

//            ResultSetMetaData meta = res.getMetaData();
//            if (!PanelDetails.isVisible()) {
//                res = db.getMovie(idTF.getText());
//                movie.getMovieFromResultset(res);
//                listMovies.add(movie);
//            } else {
//                res = db.getMovies(nomTF.getText(), stringToArrayList(acteursTF.getText()), stringToArrayList(realisateurTB.getText()), dateTF.getText());
//                while (res.next()) {
//                    movie.getMovieFromResultset(res);
//                }
//            }

            ResultSetMetaData meta = res.getMetaData();
            int numberOfColumns = meta.getColumnCount();

            Vector id = new Vector();
            for (int i = 1; i <= meta.getColumnCount(); i++)
                id.add(meta.getColumnName(i));
            Vector<Vector<Object>> v = new Vector<>();

            while (res.next()) {
                Vector<Object> vv = new Vector<>();
                for (int i = 1; i <= numberOfColumns; ++i) {
                    vv.add(res.getObject(i));
                }
                v.add(vv);
            }
            dtm.setDataVector(v, id);
            ResultatJTable.setModel(dtm);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void AjoutTable() {
        DefaultTableModel dtm = new DefaultTableModel();

        for (Movies m : listMovies) {
            Object[] o = new Object[4];
            o[0] = m.getTitle();
            o[1] = m.getOriginal_Title();
            o[2] = m.getRelease_Date();
            o[3] = m.getStatus();
            dtm.addRow(o);
        }
        ResultatJTable.setModel(dtm);
        dtm.fireTableDataChanged();
    }

    private ArrayList stringToArrayList(String items) {
        ArrayList<String> actors;
        if (items != null) {
            actors = new ArrayList<>();
            String[] tmp;
            if (items.contains(",")) tmp = items.toLowerCase().split(",");
            else if (!items.isEmpty()) {
                tmp = new String[1];
                tmp[0] = items;
            } else return null;
            Collections.addAll(actors, tmp);
        } else return null;

        return actors;
    }

    private void ResultatJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultatJTableMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1 && evt.getClickCount() == 2) {
            int row = ResultatJTable.getSelectedRow();
            String id = (String) ResultatJTable.getValueAt(row, 0);
            new DetailsFilm(db.getConnection(), id).setVisible(true);
        }
    }//GEN-LAST:event_ResultatJTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainVue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NbLabel;
    private javax.swing.JPanel PanelDetails;
    private javax.swing.JTable ResultatJTable;
    private javax.swing.JScrollPane ScrollPane1;
    private javax.swing.JLabel acteurLabel;
    private javax.swing.JTextField acteursTF;
    private javax.swing.JLabel anneeLabel;
    private javax.swing.JButton criteresButton;
    private javax.swing.JTextField dateTF;
    private javax.swing.JTextField idTF;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField nomTF;
    private javax.swing.JLabel realisateurLabel;
    private javax.swing.JTextField realisateurTB;
    private javax.swing.JLabel rechLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
